# Generated by Django 5.0.1 on 2024-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfundingweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribucion',
            name='transaccion',
            field=models.CharField(default='A'),
        ),
    ]
